name: Race Results Update

on:
  push:
    paths:
      - 'src/data/raceResults.json'
    branches: [ main ]

jobs:
  update-notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get race results data
      id: race-data
      run: |
        # Extract current results from JSON
        DATE=$(cat src/data/raceResults.json | jq -r '.currentResults.date')
        TRACK=$(cat src/data/raceResults.json | jq -r '.currentResults.track')
        HITS=$(cat src/data/raceResults.json | jq -r '.currentResults.hits')
        TOTAL_RACES=$(cat src/data/raceResults.json | jq -r '.currentResults.totalRaces')
        HIT_RATE=$(cat src/data/raceResults.json | jq -r '.currentResults.hitRate')
        PAYOUT=$(cat src/data/raceResults.json | jq -r '.currentResults.payout')
        RETURN_RATE=$(cat src/data/raceResults.json | jq -r '.currentResults.returnRate')
        
        echo "date=$DATE" >> $GITHUB_OUTPUT
        echo "track=$TRACK" >> $GITHUB_OUTPUT
        echo "hits=$HITS" >> $GITHUB_OUTPUT
        echo "total_races=$TOTAL_RACES" >> $GITHUB_OUTPUT
        echo "hit_rate=$HIT_RATE" >> $GITHUB_OUTPUT
        echo "payout=$PAYOUT" >> $GITHUB_OUTPUT
        echo "return_rate=$RETURN_RATE" >> $GITHUB_OUTPUT
        
    - name: Create update summary
      uses: actions/github-script@v7
      with:
        script: |
          const { date, track, hits, total_races, hit_rate, payout, return_rate } = {
            date: '${{ steps.race-data.outputs.date }}',
            track: '${{ steps.race-data.outputs.track }}',
            hits: '${{ steps.race-data.outputs.hits }}',
            total_races: '${{ steps.race-data.outputs.total_races }}',
            hit_rate: '${{ steps.race-data.outputs.hit_rate }}',
            payout: '${{ steps.race-data.outputs.payout }}',
            return_rate: '${{ steps.race-data.outputs.return_rate }}'
          };
          
          const summary = `
          ## 🏇 レース結果更新完了！
          
          **📅 ${date} ${track}**
          
          ### 📊 成績サマリー
          - **的中数**: ${hits}/${total_races}レース
          - **的中率**: ${hit_rate}
          - **配当金額**: ¥${Number(payout).toLocaleString()}
          - **回収率**: ${return_rate}
          
          ### 🚀 自動処理完了
          - ✅ データ検証: OK
          - ✅ サイト更新: 自動デプロイ開始
          - ✅ 統計計算: 完了
          
          ---
          *NANKANアナリティクス CMS自動化システム*
          `;
          
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: summary
          });